version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend/foodgram
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
