POST http://127.0.0.1:8000/api/auth/token/login
Content-Type: application/json

{
    "email": "user@mail.ru",
    "password": "4819411x"
}

###
GET http://127.0.0.1:8000/api/users/1/
# Authorization: Token b3871a86108fcc80dd69a8ae084d93ba8407f3d0


###
PUT http://127.0.0.1:8000/api/users/me/avatar/
Content-Type: application/json
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229

{
  "avatar": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg=="
}

###
GET http://127.0.0.1:8000/api/users/


###
GET http://127.0.0.1:8000/api/tags/

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "username": "test_user",
    "email": "user@mail.ru",
    "first_name": "test",
    "last_name": "testovich",
    "password": "4819411x"
}

###
GET http://127.0.0.1:8000/api/recipes/
# Authorization: Token 2c426106c172db713819cc88267c8e6a85958229


###
GET http://127.0.0.1:8000/api/ingredients/


###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229

{
  "ingredients": [
    {
      "id": 1988,
      "amount": 20
    },
    {
      "id": 1646,
      "amount": 5
    }
  ],
  "tags": [
    3
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Бутерброд с маслом.",
  "text": "Только лишь избранные могут себе позволить насладиться этим божественным сочетанием вкусов.",
  "cooking_time": 1
}
###
DELETE http://127.0.0.1:8000/api/recipes/16/
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229

###
GET http://127.0.0.1:8000/api/recipes/29/get-link/
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229


###
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229


###
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229

###
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229

###
GET http://127.0.0.1:8000/api/recipes/5/get-link/


###
POST http://127.0.0.1:8000/api/recipes/100/favorite/
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229

###
DELETE http://127.0.0.1:8000/api/recipes/1/favorite/
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229


###
GET http://127.0.0.1:8000/api/users/subscriptions
Authorization: Token 2c426106c172db713819cc88267c8e6a85958229


# Токен юзера Test_user - 7f93d8845df820ddedd01223c14f3f0412ad7150
###
GET http://127.0.0.1:8000/api/users/subscriptions/
Authorization: Token 7f93d8845df820ddedd01223c14f3f0412ad7150

###
GET http://127.0.0.1:8000/api/users/1/
Authorization: Token 7f93d8845df820ddedd01223c14f3f0412ad7150


###
DELETE http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 7f93d8845df820ddedd01223c14f3f0412ad7150

###
POST http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 7f93d8845df820ddedd01223c14f3f0412ad7150

###
GET http://127.0.0.1:9090/api/users