POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 562a1f13b1f43f4bb65654a139894e5ae476088f

{
    "current_password": "MySecretPas$word",
    "new_password": "thi$Pa$$w0rdW@sCh@nged"
}

###
GET http://127.0.0.1:8000/api/users
# Authorization: Token 1c9f6142fcd8d84cfd2b865cee88d20d626cd74c


###
GET http://127.0.0.1:8000/api/ingredients/?name=мяс

###
PATCH http://127.0.0.1:8000/api/recipes/1/
Authorization: Token 47c46ae279bd367557a30507c1c2033d1aeff8c1
Content-Type: application/json

{
    "ingredients": [],
    "tags": [
        2
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "Тест изменения рецепта",
    "text": "Приготовьте как нибудь эти ингредиеты, не забудьте посолить.",
    "cooking_time": 12
}


###
GET http://127.0.0.1:8000/api/recipes/




###
POST http://127.0.0.1:8000/api/users/2/subscribe/?recipes_limit=2
Authorization: Token 6fb2414224d21768ea872ca484e75a2edf09ea8f
Content-Type: application/json

###
DELETE http://127.0.0.1:8000/api/users/2/subscribe/
Authorization: Token 6fb2414224d21768ea872ca484e75a2edf09ea8f
Content-Type: application/json
###
GET http://127.0.0.1:8000/api/users/subscriptions/?recipes_limit=4
Authorization: Token 6fb2414224d21768ea872ca484e75a2edf09ea8f
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/recipes/?is_in_shopping_cart=1
Authorization: Token 930948dfa4a35f5f862a7391ea928669cc09dbc9



###
GET http://127.0.0.1:8000/api/recipes/1/
Authorization: Token 930948dfa4a35f5f862a7391ea928669cc09dbc9


###
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Authorization: Token bd507ef41133c8913424548815c1a841b038b195

###
GET http://127.0.0.1:8000/api/recipes/1/get-link/
Authorization: Token 7baeeb26fcc2ab2661a4266b5533d53bc61296eb