POST http://127.0.0.1:8000/api/auth/token/login
Content-Type: application/json

{
    "email": "alexandrov.dm@bk.ru",
    "password": "4819411x"
}

###
GET http://127.0.0.1:8000/api/users
Authorization: Token e051b74c527d0e0704e773fe61dda077c26f987d



###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token e051b74c527d0e0704e773fe61dda077c26f987d


###
PUT http://127.0.0.1:8000/api/users/me/avatar/
Content-Type: application/json
Authorization: Token e051b74c527d0e0704e773fe61dda077c26f987d

{
  "avatar": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg=="
}

###
DELETE http://127.0.0.1:8000/api/users/me/avatar/
Authorization: Token e051b74c527d0e0704e773fe61dda077c26f987d


###
GET http://127.0.0.1:8000/api/tags/

###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "username": "ololouser",
    "email": "ololo@mail.ru",
    "first_name": "ololo",
    "last_name": "ololyev",
    "password": "4819411x"
}