# Generated by Django 3.2.16 on 2024-12-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20241201_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/recipes/images', verbose_name='Картинка рецепта'),
        ),
    ]
