# Generated by Django 4.2.17 on 2024-12-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_favourites_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingred', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
