# Generated by Django 4.2.17 on 2024-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_ingredientinrecipe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField()),
                ('short_link', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'ссылки',
                'verbose_name_plural': 'ссылки',
            },
        ),
    ]
