# Generated by Django 4.2.17 on 2024-12-15 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipelinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Кол-во ингредиентов не менее 1 ед.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipelinks',
            name='original_link',
            field=models.URLField(verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='recipelinks',
            name='short_link',
            field=models.CharField(max_length=5, verbose_name='Короткая ссылка'),
        ),
    ]
