# Generated by Django 4.2.17 on 2024-12-21 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_favorite_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelinks',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='рецепт'),
            preserve_default=False,
        ),
    ]
