# Generated by Django 3.2.16 on 2024-12-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241203_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
