"""Константы проекта foodgram."""
import os

from django.conf import settings


CSV_FOLDER_PATH = os.path.join(settings.BASE_DIR, 'media\\shopping_carts')
MIN_RECIPE_COOKING_TIME = 1
MIN_RECIPE_INGREDIENT_QUANITY = 1
MAX_RECIPE_NAME_LENGHT = 256
MAX_USER_NAME_LENGTH = 150
MAX_USER_EMAIL_LENGTH = 254
MAX_INGREDIENT_NAME_LENGHT = 128
MAX_INGREDIENT_MEASUREMENT_UNIT_LENGHT = 64
MAX_TAG_NAME_LENGHT = 32
MAX_RECIPELINKS_SHORTLINK_LENGHT = 5

